name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Adicionar permissões necessárias para criar releases
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller super_hero.spec
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: SuperHero-Windows
        path: dist/
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0-windows-${{ github.run_number }}
        name: Super Hero - Windows Release v1.0.${{ github.run_number }}
        files: |
          dist/SuperHero.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 